"""Rename source to cortlandStandardSource and add cortlandVoiceSource

Revision ID: 2d63442efb4e
Revises: d82ac6136b34
Create Date: 2024-04-07 18:42:11.091642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d63442efb4e'
down_revision: Union[str, None] = 'd82ac6136b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('incidents_with_errors')
    op.drop_table('pdf')

    # Rename source to cortlandStandardSource
    op.alter_column('incident', 'source', new_column_name='cortlandStandardSource', schema='public')
    # Add cortlandVoiceSource column
    op.add_column('incident', sa.Column('cortlandVoiceSource', sa.String(), nullable=True), schema='public')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_published', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('incidents_scraped', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('incidents_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pdf_pkey'),
    sa.UniqueConstraint('path', name='pdf_path_key')
    )
    op.create_table('incidents_with_errors',
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name='incidents_with_errors_article_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='incidents_with_errors_pkey'),
    sa.UniqueConstraint('url', name='incidents_with_errors_url_key')
    )

    # Reverse the renaming
    op.alter_column('incident', 'cortlandStandardSource', new_column_name='source', schema='public')
    # Remove cortlandVoiceSource column
    op.drop_column('incident', 'cortlandVoiceSource', schema='public')

    # ### end Alembic commands ###
