"""Add unique constraint to incidents

Revision ID: a80ede8ab04c
Revises: bf26598e934a
Create Date: 2023-12-04 18:53:12.068366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80ede8ab04c'
down_revision: Union[str, None] = 'bf26598e934a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PersonAddress_AddressID_fkey', 'PersonAddress', type_='foreignkey')
    op.drop_constraint('PersonAddress_PersonID_fkey', 'PersonAddress', type_='foreignkey')
    op.create_foreign_key(None, 'PersonAddress', 'persons', ['PersonID'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'PersonAddress', 'addresses', ['AddressID'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('incidents', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'incident_reported_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('incidents', 'charges',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('incidents', 'details',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('uix_incident_details', 'incidents', ['url', 'incident_reported_date', 'charges', 'details'], schema='public')
    op.drop_constraint('incidents_accused_person_id_fkey', 'incidents', type_='foreignkey')
    op.drop_constraint('incidents_article_id_fkey', 'incidents', type_='foreignkey')
    op.create_foreign_key(None, 'incidents', 'persons', ['accused_person_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'incidents', 'article', ['article_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('incidents_from_pdf_accused_person_id_fkey', 'incidents_from_pdf', type_='foreignkey')
    op.create_foreign_key(None, 'incidents_from_pdf', 'persons', ['accused_person_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('incidents_with_errors_article_id_fkey', 'incidents_with_errors', type_='foreignkey')
    op.create_foreign_key(None, 'incidents_with_errors', 'article', ['article_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents_with_errors', schema='public', type_='foreignkey')
    op.create_foreign_key('incidents_with_errors_article_id_fkey', 'incidents_with_errors', 'article', ['article_id'], ['id'])
    op.drop_constraint(None, 'incidents_from_pdf', schema='public', type_='foreignkey')
    op.create_foreign_key('incidents_from_pdf_accused_person_id_fkey', 'incidents_from_pdf', 'persons', ['accused_person_id'], ['id'])
    op.drop_constraint(None, 'incidents', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'incidents', schema='public', type_='foreignkey')
    op.create_foreign_key('incidents_article_id_fkey', 'incidents', 'article', ['article_id'], ['id'])
    op.create_foreign_key('incidents_accused_person_id_fkey', 'incidents', 'persons', ['accused_person_id'], ['id'])
    op.drop_constraint('uix_incident_details', 'incidents', schema='public', type_='unique')
    op.alter_column('incidents', 'details',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'charges',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('incidents', 'incident_reported_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('incidents', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'PersonAddress', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'PersonAddress', schema='public', type_='foreignkey')
    op.create_foreign_key('PersonAddress_PersonID_fkey', 'PersonAddress', 'persons', ['PersonID'], ['id'])
    op.create_foreign_key('PersonAddress_AddressID_fkey', 'PersonAddress', 'addresses', ['AddressID'], ['id'])
    # ### end Alembic commands ###
